# Generated by Django 4.0.4 on 2022-06-14 14:00

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='anel',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='aneis', variations={'thumb': (350, 350), 'thumb-index': (150, 150)}, verbose_name='imagem'),
        ),
    ]
