# Generated by Django 4.0.4 on 2022-06-27 13:42

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anel_slug_alter_anel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anel',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': (124, 124), 'thumb-index': (150, 150)}, verbose_name='imagem'),
        ),
    ]
