# Generated by Django 4.0.4 on 2022-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_anel_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.AddField(
            model_name='anel',
            name='tamanho',
            field=models.ManyToManyField(to='core.tamanho'),
        ),
    ]
