# Generated by Django 4.0.4 on 2022-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tamanho_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='anel',
            name='caminho',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
    ]
