# Generated by Django 4.0.4 on 2022-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_clientes_telefone'),
        ('core', '0007_alter_tamanho_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de Atualização')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado?')),
                ('cliente', models.ForeignKey(on_delete=models.SET('Anonymous'), to='usuarios.clientes')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='CarrinhoAneis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default='', verbose_name='Quantidade')),
                ('tamanho', models.IntegerField(verbose_name='Tamanho')),
                ('anel_id', models.ForeignKey(on_delete=models.SET('0'), to='core.anel')),
                ('carrinho_id', models.ForeignKey(on_delete=models.SET('0'), to='carrinho.carrinho')),
            ],
            options={
                'verbose_name': 'Anel Vendido',
                'verbose_name_plural': 'Aneis Vendidos',
            },
        ),
    ]
