# Generated by Django 4.0.4 on 2022-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_tamanho_tamanho'),
        ('usuarios', '0004_alter_clientes_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de Atualização')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado?')),
                ('aneis', models.ManyToManyField(to='core.anel')),
                ('cliente', models.ForeignKey(on_delete=models.SET('Anonymous'), to='usuarios.clientes')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
    ]
