# Generated by Django 4.0.4 on 2022-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tamanho_tamanho'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='aneis',
        ),
        migrations.CreateModel(
            name='CarrinhoAneis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('anel_id', models.ForeignKey(on_delete=models.SET('0'), to='core.anel')),
                ('carrinho_id', models.ForeignKey(on_delete=models.SET('0'), to='carrinho.carrinho')),
            ],
            options={
                'verbose_name': 'Anel Vendido',
                'verbose_name_plural': 'Aneis Vendidos',
            },
        ),
    ]
