# Generated by Django 4.0.4 on 2022-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='sobrenome',
            field=models.CharField(max_length=50),
        ),
    ]
