# Generated by Django 4.0.4 on 2022-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_clientes_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
